### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by FerryAr** [jbaubree/vite-plugin-sitemap#35]
### Environment
OS: Manjaro Linux x64
Node : v18.7.0
PNPM : 7.10.0

Example working, because plugin installed directly from workspace, but when I'm installed this plugin via pnpm it won't run

### Log
```
failed to load config from /home/akira/NODE_PROJECT/heramom-vite/vite.config.ts
error when starting dev server:
TypeError: Sitemap is not a function
    at file:///home/akira/NODE_PROJECT/heramom-vite/vite.config.ts.timestamp-1662360498371.mjs:64:5
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async loadConfigFromBundledFile (file:///home/akira/NODE_PROJECT/heramom-vite/node_modules/.pnpm/vite@3.0.9_bckpmeqyxpddtxgilj5fird5uy/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:63077:21)
    at async loadConfigFromFile (file:///home/akira/NODE_PROJECT/heramom-vite/node_modules/.pnpm/vite@3.0.9_bckpmeqyxpddtxgilj5fird5uy/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:62963:28)
    at async resolveConfig (file:///home/akira/NODE_PROJECT/heramom-vite/node_modules/.pnpm/vite@3.0.9_bckpmeqyxpddtxgilj5fird5uy/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:62577:28)
    at async createServer (file:///home/akira/NODE_PROJECT/heramom-vite/node_modules/.pnpm/vite@3.0.9_bckpmeqyxpddtxgilj5fird5uy/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:59183:20)
    at async CAC.<anonymous> (file:///home/akira/NODE_PROJECT/heramom-vite/node_modules/.pnpm/vite@3.0.9_bckpmeqyxpddtxgilj5fird5uy/node_modules/vite/dist/node/cli.js:699:24)
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by jbaubree** [comment]
Its working for me using [vitesse-lite](https://github.com/antfu/vitesse-lite).

```
git clone https://github.com/antfu/vitesse-lite
cd vitesse-lite
pnpm i vite-plugin-sitemap -D
```

in vite.config.ts :

```
...
import Sitemap from 'vite-plugin-sitemap'
export default defineConfig({
  ...
  plugins: [
    ...
    Sitemap({
      hostname: 'https://myhost.fr/',
    })
  ]
})
```

If this is not working for you, can you provide a repo with your error ?

**Comment by jbaubree** [comment]
@FerryAr Closing for inactivity. Feel free to reopen if you have some news about your issue.

**Comment by alvinindra** [comment]
> ### Environment
> OS: Manjaro Linux x64 Node : v18.7.0 PNPM : 7.10.0
> 
> Example working, because plugin installed directly from workspace, but when I'm installed this plugin via pnpm it won't run
> 
> ### Log
> ```
> failed to load config from /home/akira/NODE_PROJECT/heramom-vite/vite.config.ts
> error when starting dev server:
> TypeError: Sitemap is not a function
>     at file:///home/akira/NODE_PROJECT/heramom-vite/vite.config.ts.timestamp-1662360498371.mjs:64:5
>     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
>     at async loadConfigFromBundledFile (file:///home/akira/NODE_PROJECT/heramom-vite/node_modules/.pnpm/vite@3.0.9_bckpmeqyxpddtxgilj5fird5uy/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:63077:21)
>     at async loadConfigFromFile (file:///home/akira/NODE_PROJECT/heramom-vite/node_modules/.pnpm/vite@3.0.9_bckpmeqyxpddtxgilj5fird5uy/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:62963:28)
>     at async resolveConfig (file:///home/akira/NODE_PROJECT/heramom-vite/node_modules/.pnpm/vite@3.0.9_bckpmeqyxpddtxgilj5fird5uy/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:62577:28)
>     at async createServer (file:///home/akira/NODE_PROJECT/heramom-vite/node_modules/.pnpm/vite@3.0.9_bckpmeqyxpddtxgilj5fird5uy/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:59183:20)
>     at async CAC.<anonymous> (file:///home/akira/NODE_PROJECT/heramom-vite/node_modules/.pnpm/vite@3.0.9_bckpmeqyxpddtxgilj5fird5uy/node_modules/vite/dist/node/cli.js:699:24)
>  ELIFECYCLE  Command failed with exit code 1.
>  ```
> ```

I have the same problem with my own project
