### ISSUE TITLE
Sitemap is not a function

### ISSUE THREAD

**Issue by alvinindra** [jbaubree/vite-plugin-sitemap#41]
### Environment
OS: Windows 10 Home Single Language
OS Build: 19043.2006
Node: v16.13.2
Pnpm: v7.6.0

### Problem
```
failed to load config from D:\Project\_Reproduction\reproduction-web-brand-issue\vite.config.js
error when starting dev server:
TypeError: Sitemap is not a function
    at file:///D:/Project/_Reproduction/reproduction-web-brand-issue/vite.config.js.timestamp-1663841008339.mjs:28:5
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)  
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadConfigFromBundledFile (file:///D:/Project/_Reproduction/reproduction-web-brand-issue/node_modules/.pnpm/vite@3.1.3_sass@1.32.12/node_modules/vite/dist/node/chunks/dep-557f29e6.js:63494:21)
    at async loadConfigFromFile (file:///D:/Project/_Reproduction/reproduction-web-brand-issue/node_modules/.pnpm/vite@3.1.3_sass@1.32.12/node_modules/vite/dist/node/chunks/dep-557f29e6.js:63380:28)      
    at async resolveConfig (file:///D:/Project/_Reproduction/reproduction-web-brand-issue/node_modules/.pnpm/vite@3.1.3_sass@1.32.12/node_modules/vite/dist/node/chunks/dep-557f29e6.js:62997:28)
    at async createServer (file:///D:/Project/_Reproduction/reproduction-web-brand-issue/node_modules/.pnpm/vite@3.1.3_sass@1.32.12/node_modules/vite/dist/node/chunks/dep-557f29e6.js:62063:20)
    at async CAC.<anonymous> (file:///D:/Project/_Reproduction/reproduction-web-brand-issue/node_modules/.pnpm/vite@3.1.3_sass@1.32.12/node_modules/vite/dist/node/cli.js:700:24)
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction
https://github.com/alvinindra/reproduction-web-brand-issue

**Comment by alvinindra** [comment]
I also tried using the [vite-plugin-pages-sitemap](https://github.com/jbaubree/vite-plugin-pages-sitemap) plugin and found the same problem

**Comment by jbaubree** [comment]
Hi, with your configuration, you have to call Sitemap.default(). I will create a new build with auto importing as default for next version. Thanks for reporting and fill free to close this issue if it's ok for you.

**Comment by alvinindra** [comment]
Thank you, I've tried it and it works

**Comment by jbaubree** [comment]
@alvinindra can you try to use v0.3.0 without .default and say me if its ok for you ?

**Comment by alvinindra** [comment]
It works in vite-plugin-sitemap. But I'm use [vite-plugin-pages-sitemap](https://github.com/jbaubree/vite-plugin-pages-sitemap) for now
